### ISSUE TITLE
active record deprecation notice with 2.3.5

### ISSUE THREAD

**Issue by zilkey** [nakajima/acts_as_fu#3]
activerecord should be active_record

**Comment by nakajima** [comment]
Cry about it. No actually I'll fix this tonight. :)

**Comment by flavorjones** [comment]
This is brokened in Rails 3! I can has fix?

Pull request coming your way ...

**Comment by flavorjones** [comment]
see 
http://github.com/flavorjones/acts_as_fu/commit/0ade973228fa5747ea3f0c00c6b0f34489cc4dda

and, ultimately: http://github.com/flavorjones/acts_as_fu/commit/8af2ca3f59f9cfbefbf163268e690a444ac31b6d

**Comment by flavorjones** [comment]
"activerecord" -> "active_record". closed by 0ade973228fa5747ea3f0c00c6b0f34489cc4dda.
